### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by dougkite** [rekall-innovations/rekall-capstone#5]
Trying to install from commit. error says "package directory 'capstone' does not exist".

Trying to install rekall from git head. It says a dependency is rekall-capstone (3.0.5.post2) but the lastest one in PyPI is rekall-capstone (3.0.5.post1).

so I tried to install with:
pip install git+git://github.com/rekall-innovations/rekall-capstone.git@7069a448731dfcbedae0e700e819849955488594

error received:

(rk) user@kali:~/rekall/rekall-core# pip install git+git://github.com/rekall-innovations/rekall-capstone.git@7069a448731dfcbedae0e700e819849955488594
Collecting git+git://github.com/rekall-innovations/rekall-capstone.git@7069a448731dfcbedae0e700e819849955488594
  Cloning git://github.com/rekall-innovations/rekall-capstone.git (to 7069a448731dfcbedae0e700e819849955488594) to /tmp/pip-w3uzso0g-build
  Could not find a tag or branch '7069a448731dfcbedae0e700e819849955488594', assuming commit.
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/rekall_capstone.egg-info
    writing pip-egg-info/rekall_capstone.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/rekall_capstone.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/rekall_capstone.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/rekall_capstone.egg-info/SOURCES.txt'
    error: package directory 'capstone' does not exist
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-w3uzso0g-build/

**Comment by scudette** [comment]
To install from git head you need to first build the package

Python setup.py sdist
Then you install the package
Pip install dist/rekall-capstone...

**Comment by dougkite** [comment]
Thank you that worked.
